export const runtime = 'edge';

import { NextRequest, NextResponse } from 'next/server';
import { getDb } from '@/lib/db';

export async function GET(
  _req: NextRequest,
  { params }: { params: { id: string } },
) {
  let sql;
  try {
    sql = getDb();
  } catch {
    return new NextResponse('Sharing not configured', { status: 503 });
  }

  const rows = await sql`
    SELECT name, content, audio_url
    FROM shares
    WHERE id = ${params.id}
      AND expires_at > NOW()
  `;

  if (!rows.length) {
    return new NextResponse('Not found or expired', { status: 404 });
  }

  const row = rows[0] as {
    name: string;
    content: { lines?: unknown[] };
    audio_url: string | null;
  };

  if (!row.audio_url) {
    return new NextResponse('Audio not yet uploaded', { status: 404 });
  }

  const lineCount = Array.isArray(row.content?.lines) ? row.content.lines.length : 0;
  // Rough estimate: 4 seconds per dialogue line
  const durationSecs = lineCount * 4;
  const minutes = Math.floor(durationSecs / 60);
  const seconds = durationSecs % 60;
  const durationFormatted = `${minutes}:${String(seconds).padStart(2, '0')}`;

  const pubDate = new Date().toUTCString();
  const escapedName = row.name
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
  xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
  xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>${escapedName}</title>
    <description>${escapedName} — generated by Narrator</description>
    <language>en</language>
    <pubDate>${pubDate}</pubDate>
    <itunes:explicit>no</itunes:explicit>
    <item>
      <title>${escapedName}</title>
      <description>${escapedName}</description>
      <pubDate>${pubDate}</pubDate>
      <enclosure url="${row.audio_url}" type="audio/mpeg" length="0" />
      <guid>${params.id}</guid>
      <itunes:explicit>no</itunes:explicit>
      <itunes:duration>${durationFormatted}</itunes:duration>
    </item>
  </channel>
</rss>`;

  return new NextResponse(xml, {
    headers: { 'Content-Type': 'application/rss+xml; charset=utf-8' },
  });
}
